apiVersion: apps/v1
kind: Deployment
metadata:
  name: preceni-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preceni-auth
  template:
    metadata:
      labels:
        app: preceni-auth
    spec:
      containers:
        - image: vidvidex/preceni-auth:2023-12-24-17-11-32
          name: preceni-auth
          env:
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: database-name
                key: db-name
                
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: database-host
                key: db-host

          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: database-port
                key: db-port

          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: database-user
                key: db-user

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-password
                key: db-password

          - name: AUTH_SERVICE_PORT
            valueFrom:
              secretKeyRef:
                name: auth-port
                key: auth-service-port

          - name: AUTH_SERVICE_DEBUG
            valueFrom:
              secretKeyRef:
                name: auth-debug
                key: auth-service-debug

          - name: PYTHONUNBUFFERED
            value: "TRUE"

          ports:
            - containerPort: 5001
              name: preceni-auth

          livenessProbe:
            httpGet:
              path: /auth/health/live
              port: preceni-auth
            failureThreshold: 2
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /auth/health/live
              port: preceni-auth
            failureThreshold: 2
            initialDelaySeconds: 20
            periodSeconds: 30
---

apiVersion: v1
kind: Service
metadata:
  name: preceni-auth-lb
spec:
  type: LoadBalancer
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
  selector:
    app: preceni-auth
